
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hospital-sys
      MYSQL_USER: user
      MYSQL_PASSWORD: usr
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  tomcat:
    build: .
    container_name: tomcat-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
#    volumes:
#      - ./target/hospital-sys.war:/usr/local/tomcat/webapps/ROOT.war
    volumes:
      - ./target/digital-hospital-jee-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/digital-hospital-jee.war
      - ./target/hospital-sys.war:/usr/local/tomcat/webapps/hospital-sys.war

    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
